name: PotterWorldSpells
version: ${project.version}
main: me.nanigans.potterworldspells.PotterWorldSpells
api-version: 1.16
authors: [ProNanigans]
description: Remake of potterworld spells better this time
depend: [EffectLib]
commands:
  wand:
    description: Gives you a new wand!
    usage: /wand
  particlecolor:
    description: Sets you wand particle to the given hex color value
    usage: /particlecolor 000FFF
    aliases: [pc, partcol, wandcolor, wc]